import React from 'react';

export const dbStore = {
	centers: [
		{
			name: 'Accra',
			code: 'ACC',
			blocks: 3,
		},
		{
			name: 'Volta',
			code: 'VR',
			blocks: 3,
		},
		{
			name: 'Kumasi',
			code: 'KMA',
			blocks: 3,
		},
	],
	programmes: [
		{
			name: 'Computer Engineering',
			code: 'COE',
			year: 1,
		},
		{
			name: 'Computer Engineering',
			code: 'COE',
			year: 2,
		},
		{
			name: 'Computer Engineering',
			code: 'COE',
			year: 3,
		},
		{
			name: 'Computer Engineering',
			code: 'COE',
			year: 4,
		},
		{
			name: 'Biomedical Engineering',
			code: 'COE',
			year: 1,
		},
		{
			name: 'Biomedical Engineering',
			code: 'COE',
			year: 2,
		},
		{
			name: 'Biomedical Engineering',
			code: 'COE',
			year: 3,
		},
		{
			name: 'Biomedical Engineering',
			code: 'COE',
			year: 4,
		},
		{
			name: 'Electrical Engineering',
			code: 'COE',
			year: 1,
		},
		{
			name: 'Electrical Engineering',
			code: 'COE',
			year: 2,
		},
		{
			name: 'Electrical Engineering',
			code: 'COE',
			year: 3,
		},
		{
			name: 'Electrical Engineering',
			code: 'COE',
			year: 4,
		},
		{
			name: 'Telecom Engineering',
			code: 'COE',
			year: 1,
		},
		{
			name: 'Telecom Engineering',
			code: 'COE',
			year: 2,
		},
		{
			name: 'Telecom Engineering',
			code: 'COE',
			year: 3,
		},
		{
			name: 'Telecom Engineering',
			code: 'COE',
			year: 4,
		},
	],
	courses: [
		{
			title: 'Programming With C++',
			code: 'DIT 112',
			semester: 1,
		},
		{
			title: 'Communication Skills II',
			code: 'ENG 124',
			semester: 1,
		},
		{
			title: 'Database Systems',
			code: 'GE 464',
			semester: 1,
		},
		{
			title: 'Calculus with Several Variables',
			code: 'MATH 252',
			semester: 1,
		},
		{
			title: 'Project Management',
			code: 'CEMBA 574',
			semester: 1,
		},
		{
			title: 'Applied Electricity',
			code: 'COE 124',
			semester: 1,
		},
		{
			title: 'Semiconductor Devices',
			code: 'COE 271',
			semester: 1,
		},
		{
			title: 'Logistics Management',
			code: 'ISD 370',
			semester: 1,
		},
		{
			title: 'Food Laws',
			code: 'FQM 576',
			semester: 1,
		},
		{
			title: 'Asynchronous and DC Machines',
			code: 'EE 261',
			semester: 1,
		},
		{
			title: 'Basic Electronics',
			code: 'COE 158',
			semester: 2,
		},
		{
			title: 'Embedded Systems',
			code: 'COE 371',
			semester: 2,
		},
		{
			title: 'Operating Systems',
			code: 'COE 370',
			semester: 2,
		},
		{
			title: 'Digital Signal Processing',
			code: 'COE 452',
			semester: 2,
		},
		{
			title: 'Controls System',
			code: 'EE 361',
			semester: 2,
		},
	],
	course_allocations: [
		{
			name: 'Computer Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Computer Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
			sem2: ['C Programming', 'Database Systems', 'C Programming', 'Database Systems'],
		},
		{
			name: 'Computer Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Computer Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Biomedical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Biomedical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Biomedical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Biomedical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Electrical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Electrical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Electrical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Electrical Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Telecom Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Telecom Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Telecom Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
		{
			name: 'Telecom Engineering',
			sem1: [
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
			],
			sem2: [
				'Database Systems',
				'Basic Electronics',
				'C Programming',
				'Database Systems',
				'C Programming',
				'Database Systems',
			],
		},
	],
};
