import React from "react";

export const dbStore = {
  centers: [
    {
      name: "Accra",
      code: "ACC",
      blocks: 3,
    },
    {
      name: "Volta",
      code: "VR",
      blocks: 3,
    },
    {
      name: "Kumasi",
      code: "KMA",
      blocks: 3,
    },
  ],
  venues: [
    { center: "Accra", name: "Room 2", capacity: 50 },
    {
      center: "Accra",
      name: "Room 3",
      capacity: 50,
    },
    {
      center: "Accra",
      name: "Room 4",
      capacity: 50,
    },
  ],
  programmes: [
    {
      name: "Computer Engineering",
      code: "COE",
      year: 1,
    },
    {
      name: "Computer Engineering",
      code: "COE",
      year: 2,
    },
    {
      name: "Computer Engineering",
      code: "COE",
      year: 3,
    },
    {
      name: "Computer Engineering",
      code: "COE",
      year: 4,
    },
    {
      name: "Biomedical Engineering",
      code: "COE",
      year: 1,
    },
    {
      name: "Biomedical Engineering",
      code: "COE",
      year: 2,
    },
    {
      name: "Biomedical Engineering",
      code: "COE",
      year: 3,
    },
    {
      name: "Biomedical Engineering",
      code: "COE",
      year: 4,
    },
    {
      name: "Electrical Engineering",
      code: "COE",
      year: 1,
    },
    {
      name: "Electrical Engineering",
      code: "COE",
      year: 2,
    },
    {
      name: "Electrical Engineering",
      code: "COE",
      year: 3,
    },
    {
      name: "Electrical Engineering",
      code: "COE",
      year: 4,
    },
    {
      name: "Telecom Engineering",
      code: "COE",
      year: 1,
    },
    {
      name: "Telecom Engineering",
      code: "COE",
      year: 2,
    },
    {
      name: "Telecom Engineering",
      code: "COE",
      year: 3,
    },
    {
      name: "Telecom Engineering",
      code: "COE",
      year: 4,
    },
  ],
  courses: [
    {
      title: "Programming With C++",
      code: "DIT 112",
      semester: 1,
    },
    {
      title: "Communication Skills II",
      code: "ENG 124",
      semester: 1,
    },
    {
      title: "Database Systems",
      code: "GE 464",
      semester: 1,
    },
    {
      title: "Calculus with Several Variables",
      code: "MATH 252",
      semester: 1,
    },
    {
      title: "Project Management",
      code: "CEMBA 574",
      semester: 1,
    },
    {
      title: "Applied Electricity",
      code: "COE 124",
      semester: 1,
    },
    {
      title: "Semiconductor Devices",
      code: "COE 271",
      semester: 1,
    },
    {
      title: "Logistics Management",
      code: "ISD 370",
      semester: 1,
    },
    {
      title: "Food Laws",
      code: "FQM 576",
      semester: 1,
    },
    {
      title: "Asynchronous and DC Machines",
      code: "EE 261",
      semester: 1,
    },
    {
      title: "Basic Electronics",
      code: "COE 158",
      semester: 2,
    },
    {
      title: "Embedded Systems",
      code: "COE 371",
      semester: 2,
    },
    {
      title: "Operating Systems",
      code: "COE 370",
      semester: 2,
    },
    {
      title: "Digital Signal Processing",
      code: "COE 452",
      semester: 2,
    },
    {
      title: "Controls System",
      code: "EE 361",
      semester: 2,
    },
  ],
  computer1: [
    // {
    //   id: 1,
    //   title: "MID SEM",
    //   start: new Date(2019, 2, 23, 7, 0, 0),
    //   end: new Date(2019, 2, 23, 9, 0, 0),
    // },
    // {
    //   id: 2,
    //   title: "MID SEM",
    //   start: new Date(2019, 2, 23, 9, 30, 0),
    //   end: new Date(2019, 2, 23, 12, 0, 0),
    // },
    // {
    //   id: 3,
    //   title: "END SEM",
    //   start: new Date(2019, 2, 23, 12, 0, 0),
    //   end: new Date(2019, 2, 23, 2, 0, 0),
    // },
    // {
    //   id: 4,
    //   title: "END SEM",
    //   start: new Date(2019, 2, 24, 7, 0, 0),
    //   end: new Date(2019, 2, 23, 8, 0, 0),
    // },
    // {
    //   id: 5,
    //   title: "END SEM",
    //   start: new Date(2019, 2, 24, 9, 30, 0),
    //   end: new Date(2019, 2, 23, 10, 0, 0),
	// },
	{
	  id: 1,
	  title: 'Long Event',
	  start: new Date(2015, 3, 7),
	  end: new Date(2015, 3, 10),
	},

	{
	  id: 2,
	  title: 'DTS STARTS',
	  start: new Date(2016, 2, 13, 0, 0, 0),
	  end: new Date(2016, 2, 20, 0, 0, 0),
	},

	{
	  id: 3,
	  title: 'DTS ENDS',
	  start: new Date(2016, 10, 6, 0, 0, 0),
	  end: new Date(2016, 10, 13, 0, 0, 0),
	},

	{
	  id: 4,
	  title: 'Some Event',
	  start: new Date(2015, 3, 9, 0, 0, 0),
	  end: new Date(2015, 3, 10, 0, 0, 0),
	},
	{
	  id: 5,
	  title: 'Conference',
	  start: new Date(2015, 3, 11),
	  end: new Date(2015, 3, 13),
	  desc: 'Big conference for important people',
	},
	{
	  id: 6,
	  title: 'Meeting',
	  start: new Date(2015, 3, 12, 10, 30, 0, 0),
	  end: new Date(2015, 3, 12, 12, 30, 0, 0),
	  desc: 'Pre-meeting meeting, to prepare for the meeting',
	},
  ],
  course_allocations: [
    {
      name: "Computer Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Computer Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Computer Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Computer Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Biomedical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Biomedical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Biomedical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Biomedical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Electrical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Electrical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Electrical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Electrical Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Telecom Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Telecom Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Telecom Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
    {
      name: "Telecom Engineering",
      sem_1: [
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
      ],
      sem_2: [
        "Database Systems",
        "Basic Electronics",
        "C Programming",
        "Database Systems",
        "C Programming",
        "Database Systems",
      ],
    },
  ],
};
